title: CE Projects - UoP
description: ""
baseurl: "/r" # the subpath of your site, e.g. /blog
url: "https://cepdnaclk.github.io"


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"


# jekyll-readme-index
# https://github.com/benbalter/jekyll-readme-index
readme_index:
  enabled:          true
  remove_originals: false
  with_frontmatter: false

plugins:
  - jekyll-readme-index

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false
  input: GFM
